project:
  type: website
  resources:
    - files/*   # so your PDF gets copied when you render

website:
  title: "Anugraha Samuel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Assignments
        menu:
          - href: assignment1.qmd
            text: Assignment 1
          - href: assignment2.qmd
            text: Assignment 2
          - href: assignment3.qmd
            text: Assignment 3
          - href: assignment4.qmd
            text: Assignment 4
          - href: assignment5.qmd
            text: Assignment 5
          - href: assignment6.qmd
            text: Assignment 6

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual
